# Generated by Django 2.2.2 on 2020-04-23 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langclassifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_ObjectID', models.IntegerField()),
                ('comment_objID', models.IntegerField()),
                ('emoji_comment_list', models.TextField()),
                ('pure_emoji_list', models.TextField()),
                ('emoji_pure_arabic_list', models.TextField()),
                ('emoji_pure_english_list', models.TextField()),
                ('emoji_mixed_lang_list', models.TextField()),
                ('emoji_arabic_with_others_list', models.TextField()),
                ('emoji_english_with_others_list', models.TextField()),
                ('emoji_ar_en_list', models.TextField()),
                ('emoji_exceptions_list', models.TextField()),
                ('emoji_other_language_list', models.TextField()),
                ('emoji_useless_comment_list', models.TextField()),
                ('pure_arabic_list', models.TextField()),
                ('pure_english_list', models.TextField()),
                ('mixed_lang_list', models.TextField()),
                ('exceptions_list', models.TextField()),
                ('other_language_list', models.TextField()),
                ('useless_comment_list', models.TextField()),
                ('arabic_with_others_list', models.TextField()),
                ('english_with_others_list', models.TextField()),
                ('ar_en_list', models.TextField()),
                ('comment_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comments.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_Object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comments.Videoinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Commentclassifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_ObjectID', models.IntegerField()),
                ('comment_objID', models.IntegerField()),
                ('comment_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comments.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_Object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comments.Videoinformation')),
            ],
        ),
    ]
